server:
  port: 7001
eureka:
  instance:
    hostname: eureka7001.com #eureka服务端的实例名称
  client:
    #false表示不向注册中心注册自己。
    register-with-eureka: false
    #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址。
      #defaultZone: http://${eureka.instance.hostname}:7002/eureka/  #http://localhost:7001/eureka/
      defaultZone: http://eureka7002.com:7002/eureka/  #http://localhost:7002/eureka/
      #此处实现两台eureka互相注册，需要填写对方的地址
